#ifndef APP_CONFIG_H
#define APP_CONFIG_H

// Define APP_MAVLINK_ENABLED to include and activate the MAVLink service.
#ifdef APP_MAVLINK_ENABLED
#define APP_MAVLINK_SYSTEM_ID 1U
#define APP_MAVLINK_COMPONENT_ID 191U
#define APP_MAVLINK_HEARTBEAT_INTERVAL_MS 1000U
#define APP_MAVLINK_MAGNETOMETER_INTERVAL_MS 200U
#define APP_MAVLINK_STATUS_INTERVAL_MS 10000U
#define APP_MAVLINK_ATTITUDE_INTERVAL_US 100000U
#define APP_MAVLINK_ATTITUDE_REQUEST_RETRY_MS 5000U
#define APP_MAVLINK_TX_TIMEOUT_MS 100U
#endif

#endif
